### ISSUE TITLE
Is there an drmed epub sample ?

### ISSUE THREAD

**Issue by wzhsunn** [IDPF/epub3-samples#2] opened 2015-04-13 07:27 UTC
Thank you .

I want to test this when I using an epub reader open it ( for example ibook, it tell me it is drmed ).

**Comment by mattgarrish** [comment] 2015-04-13 12:54
Although epub allows for DRM, DRM itself isn't a feature of EPUB 3. For that reason, we haven't included any DRMed samples in this project, as the goal is to provide content that anyone can review/load.

**Comment by wzhsunn** [comment] 2015-04-14 00:38
I just want an drmed file and follow it create one. It should be report "drmed file" when open in iBooks or adobe edition reader .

**Comment by ehidalgo-vibal** [comment] 2015-04-14 00:53
If you can check epub3 spec here: http://www.idpf.org/epub/30/spec/epub30-ocf.html#sec-container-metainf-rights.xml 

It will tell you how e-readers determine if file is DRM protected.

> On Apr 14, 2015, at 8:38 AM, sunny notifications@github.com wrote:
> 
> I just want an drmed file and follow it create one. It should be report "drmed file" when open in iBooks or adobe edition reader .
> 
> —
> Reply to this email directly or view it on GitHub.

## 

 This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the sender. Please 
note that any views or opinions presented in this email are solely those of 
the author and do not necessarily represent those of the company. Finally, the 
recipient should check this email and any attachments for the presence of 
viruses. The company accepts no liability for any damage caused by any 
virus transmitted by this email.

**Comment by wzhsunn** [comment] 2015-04-14 01:30
http://www.idpf.org/epub/301/spec/epub-ocf.html#example 
I make a test.epub by the 'Appendix B. Example' , when I open it with iBooks , it reporst corrupt file but no t drmed file .

You can download it from here :http://pan.baidu.com/s/1eQJ93hg.

**Comment by wzhsunn** [comment] 2015-04-15 02:16
@ehidalgo-vibal  Could you help me please ?

**Comment by timofonic** [comment] 2016-01-13 06:30
Does it mean every EPUB3 implementation features it's own different DRM? What a mess, a standard one...

**Comment by mattgarrish** [comment] 2017-06-05 22:04
Closing as this repository is only for open source content. We won't be hosting DRMed content.

**Closed as completed by mattgarrish** 2017-06-05 22:04 UTC
